package com.boob.sw.model;

import java.util.Date;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.u_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.g_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Long gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.num
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.u_id
     *
     * @return the value of cart.u_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.u_id
     *
     * @param uId the value for cart.u_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.g_id
     *
     * @return the value of cart.g_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.g_id
     *
     * @param gId the value for cart.g_id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.num
     *
     * @return the value of cart.num
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.num
     *
     * @param num the value for cart.num
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.gmt_created
     *
     * @return the value of cart.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.gmt_created
     *
     * @param gmtCreated the value for cart.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.gmt_modified
     *
     * @return the value of cart.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.gmt_modified
     *
     * @param gmtModified the value for cart.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}