package com.boob.sw.model;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.u_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.g_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Long gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.score
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.gmt_created
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.gmt_modified
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.u_id
     *
     * @return the value of comments.u_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.u_id
     *
     * @param uId the value for comments.u_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.g_id
     *
     * @return the value of comments.g_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Long getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.g_id
     *
     * @param gId the value for comments.g_id
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setgId(Long gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.score
     *
     * @return the value of comments.score
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.score
     *
     * @param score the value for comments.score
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.gmt_created
     *
     * @return the value of comments.gmt_created
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.gmt_created
     *
     * @param gmtCreated the value for comments.gmt_created
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.gmt_modified
     *
     * @return the value of comments.gmt_modified
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.gmt_modified
     *
     * @param gmtModified the value for comments.gmt_modified
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}