package com.boob.sw.model;

public class GoodsWithBLOBs extends Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.get
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String get;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String show;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.get
     *
     * @return the value of goods.get
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getGet() {
        return get;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.get
     *
     * @param get the value for goods.get
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setGet(String get) {
        this.get = get == null ? null : get.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.show
     *
     * @return the value of goods.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.show
     *
     * @param show the value for goods.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }
}