package com.boob.sw.model;

import java.util.Date;

public class Music {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.author
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Integer love;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.id
     *
     * @return the value of music.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.id
     *
     * @param id the value for music.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.name
     *
     * @return the value of music.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.name
     *
     * @param name the value for music.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.author
     *
     * @return the value of music.author
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.author
     *
     * @param author the value for music.author
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.love
     *
     * @return the value of music.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Integer getLove() {
        return love;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.love
     *
     * @param love the value for music.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setLove(Integer love) {
        this.love = love;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.gmt_created
     *
     * @return the value of music.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.gmt_created
     *
     * @param gmtCreated the value for music.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.gmt_modified
     *
     * @return the value of music.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.gmt_modified
     *
     * @param gmtModified the value for music.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}