package com.boob.sw.model;

import java.util.Date;

public class OrganMidSuper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_super.id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_super.o_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_super.s_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    private Long sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_super.gmt_created
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_super.gmt_modified
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_super.id
     *
     * @return the value of organ_mid_super.id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_super.id
     *
     * @param id the value for organ_mid_super.id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_super.o_id
     *
     * @return the value of organ_mid_super.o_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_super.o_id
     *
     * @param oId the value for organ_mid_super.o_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_super.s_id
     *
     * @return the value of organ_mid_super.s_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public Long getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_super.s_id
     *
     * @param sId the value for organ_mid_super.s_id
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public void setsId(Long sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_super.gmt_created
     *
     * @return the value of organ_mid_super.gmt_created
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_super.gmt_created
     *
     * @param gmtCreated the value for organ_mid_super.gmt_created
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_super.gmt_modified
     *
     * @return the value of organ_mid_super.gmt_modified
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_super.gmt_modified
     *
     * @param gmtModified the value for organ_mid_super.gmt_modified
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}