package com.boob.sw.model;

public class OrganizationWithBLOBs extends Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String honor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.honor
     *
     * @return the value of organization.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.honor
     *
     * @param honor the value for organization.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.show
     *
     * @return the value of organization.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.show
     *
     * @param show the value for organization.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.description
     *
     * @return the value of organization.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.description
     *
     * @param description the value for organization.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}