package com.boob.sw.model;

import java.util.Date;

public class OrganMidUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_user.id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_user.o_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_user.u_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_user.gmt_created
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_mid_user.gmt_modified
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_user.id
     *
     * @return the value of organ_mid_user.id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_user.id
     *
     * @param id the value for organ_mid_user.id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_user.o_id
     *
     * @return the value of organ_mid_user.o_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_user.o_id
     *
     * @param oId the value for organ_mid_user.o_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_user.u_id
     *
     * @return the value of organ_mid_user.u_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_user.u_id
     *
     * @param uId the value for organ_mid_user.u_id
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_user.gmt_created
     *
     * @return the value of organ_mid_user.gmt_created
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_user.gmt_created
     *
     * @param gmtCreated the value for organ_mid_user.gmt_created
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_mid_user.gmt_modified
     *
     * @return the value of organ_mid_user.gmt_modified
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_mid_user.gmt_modified
     *
     * @param gmtModified the value for organ_mid_user.gmt_modified
     *
     * @mbg.generated Tue Jan 21 13:29:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}