package com.boob.sw.model;

import java.util.Date;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.reveal
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private String reveal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Integer love;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.name
     *
     * @return the value of photo.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.name
     *
     * @param name the value for photo.name
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.reveal
     *
     * @return the value of photo.reveal
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getReveal() {
        return reveal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.reveal
     *
     * @param reveal the value for photo.reveal
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setReveal(String reveal) {
        this.reveal = reveal == null ? null : reveal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.love
     *
     * @return the value of photo.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Integer getLove() {
        return love;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.love
     *
     * @param love the value for photo.love
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setLove(Integer love) {
        this.love = love;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.gmt_created
     *
     * @return the value of photo.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.gmt_created
     *
     * @param gmtCreated the value for photo.gmt_created
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.gmt_modified
     *
     * @return the value of photo.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.gmt_modified
     *
     * @param gmtModified the value for photo.gmt_modified
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}