package com.boob.sw.model;

import java.util.Date;

public class SendUs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.u_id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.email
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.content
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_us.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.id
     *
     * @return the value of send_us.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.id
     *
     * @param id the value for send_us.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.u_id
     *
     * @return the value of send_us.u_id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.u_id
     *
     * @param uId the value for send_us.u_id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.name
     *
     * @return the value of send_us.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.name
     *
     * @param name the value for send_us.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.email
     *
     * @return the value of send_us.email
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.email
     *
     * @param email the value for send_us.email
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.content
     *
     * @return the value of send_us.content
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.content
     *
     * @param content the value for send_us.content
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.gmt_created
     *
     * @return the value of send_us.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.gmt_created
     *
     * @param gmtCreated the value for send_us.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_us.gmt_modified
     *
     * @return the value of send_us.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_us.gmt_modified
     *
     * @param gmtModified the value for send_us.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}