package com.boob.sw.model;

import java.util.Date;

public class Shopper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.name
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.description
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.o_id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.score
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.avatar
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.gmt_created
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.gmt_modified
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.id
     *
     * @return the value of shopper.id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.id
     *
     * @param id the value for shopper.id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.name
     *
     * @return the value of shopper.name
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.name
     *
     * @param name the value for shopper.name
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.description
     *
     * @return the value of shopper.description
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.description
     *
     * @param description the value for shopper.description
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.o_id
     *
     * @return the value of shopper.o_id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.o_id
     *
     * @param oId the value for shopper.o_id
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.score
     *
     * @return the value of shopper.score
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.score
     *
     * @param score the value for shopper.score
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.avatar
     *
     * @return the value of shopper.avatar
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.avatar
     *
     * @param avatar the value for shopper.avatar
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.gmt_created
     *
     * @return the value of shopper.gmt_created
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.gmt_created
     *
     * @param gmtCreated the value for shopper.gmt_created
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.gmt_modified
     *
     * @return the value of shopper.gmt_modified
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.gmt_modified
     *
     * @param gmtModified the value for shopper.gmt_modified
     *
     * @mbg.generated Sat Jan 18 15:04:38 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}