package com.boob.sw.model;

public class ShopClassWithBLOBs extends ShopClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_class.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_class.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String show;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_class.description
     *
     * @return the value of shop_class.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_class.description
     *
     * @param description the value for shop_class.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_class.show
     *
     * @return the value of shop_class.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_class.show
     *
     * @param show the value for shop_class.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }
}