package com.boob.sw.model;

import java.util.Date;

public class Superior {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.avatar
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.country
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.interal
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Integer interal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.honor
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String honor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.show
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.description
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.id
     *
     * @return the value of superior.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.id
     *
     * @param id the value for superior.id
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.name
     *
     * @return the value of superior.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.name
     *
     * @param name the value for superior.name
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.avatar
     *
     * @return the value of superior.avatar
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.avatar
     *
     * @param avatar the value for superior.avatar
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.country
     *
     * @return the value of superior.country
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.country
     *
     * @param country the value for superior.country
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.interal
     *
     * @return the value of superior.interal
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Integer getInteral() {
        return interal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.interal
     *
     * @param interal the value for superior.interal
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setInteral(Integer interal) {
        this.interal = interal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.honor
     *
     * @return the value of superior.honor
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.honor
     *
     * @param honor the value for superior.honor
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.show
     *
     * @return the value of superior.show
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.show
     *
     * @param show the value for superior.show
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.description
     *
     * @return the value of superior.description
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.description
     *
     * @param description the value for superior.description
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.gmt_created
     *
     * @return the value of superior.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.gmt_created
     *
     * @param gmtCreated the value for superior.gmt_created
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.gmt_modified
     *
     * @return the value of superior.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.gmt_modified
     *
     * @param gmtModified the value for superior.gmt_modified
     *
     * @mbg.generated Wed Jan 22 14:09:59 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}