package com.boob.sw.model;

public class SuperiorWithBLOBs extends Superior {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String honor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superior.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.honor
     *
     * @return the value of superior.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.honor
     *
     * @param honor the value for superior.honor
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.show
     *
     * @return the value of superior.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.show
     *
     * @param show the value for superior.show
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setShow(String show) {
        this.show = show == null ? null : show.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superior.description
     *
     * @return the value of superior.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superior.description
     *
     * @param description the value for superior.description
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}