package com.boob.sw.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TargetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public TargetExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("u_id is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("u_id is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Long value) {
            addCriterion("u_id =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Long value) {
            addCriterion("u_id <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Long value) {
            addCriterion("u_id >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Long value) {
            addCriterion("u_id >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Long value) {
            addCriterion("u_id <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Long value) {
            addCriterion("u_id <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Long> values) {
            addCriterion("u_id in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Long> values) {
            addCriterion("u_id not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Long value1, Long value2) {
            addCriterion("u_id between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Long value1, Long value2) {
            addCriterion("u_id not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andPushTargetIsNull() {
            addCriterion("push_target is null");
            return (Criteria) this;
        }

        public Criteria andPushTargetIsNotNull() {
            addCriterion("push_target is not null");
            return (Criteria) this;
        }

        public Criteria andPushTargetEqualTo(String value) {
            addCriterion("push_target =", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetNotEqualTo(String value) {
            addCriterion("push_target <>", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetGreaterThan(String value) {
            addCriterion("push_target >", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetGreaterThanOrEqualTo(String value) {
            addCriterion("push_target >=", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetLessThan(String value) {
            addCriterion("push_target <", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetLessThanOrEqualTo(String value) {
            addCriterion("push_target <=", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetLike(String value) {
            addCriterion("push_target like", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetNotLike(String value) {
            addCriterion("push_target not like", value, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetIn(List<String> values) {
            addCriterion("push_target in", values, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetNotIn(List<String> values) {
            addCriterion("push_target not in", values, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetBetween(String value1, String value2) {
            addCriterion("push_target between", value1, value2, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPushTargetNotBetween(String value1, String value2) {
            addCriterion("push_target not between", value1, value2, "pushTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetIsNull() {
            addCriterion("pull_target is null");
            return (Criteria) this;
        }

        public Criteria andPullTargetIsNotNull() {
            addCriterion("pull_target is not null");
            return (Criteria) this;
        }

        public Criteria andPullTargetEqualTo(String value) {
            addCriterion("pull_target =", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetNotEqualTo(String value) {
            addCriterion("pull_target <>", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetGreaterThan(String value) {
            addCriterion("pull_target >", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetGreaterThanOrEqualTo(String value) {
            addCriterion("pull_target >=", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetLessThan(String value) {
            addCriterion("pull_target <", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetLessThanOrEqualTo(String value) {
            addCriterion("pull_target <=", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetLike(String value) {
            addCriterion("pull_target like", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetNotLike(String value) {
            addCriterion("pull_target not like", value, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetIn(List<String> values) {
            addCriterion("pull_target in", values, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetNotIn(List<String> values) {
            addCriterion("pull_target not in", values, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetBetween(String value1, String value2) {
            addCriterion("pull_target between", value1, value2, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andPullTargetNotBetween(String value1, String value2) {
            addCriterion("pull_target not between", value1, value2, "pullTarget");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneIsNull() {
            addCriterion("short_period_one is null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneIsNotNull() {
            addCriterion("short_period_one is not null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneEqualTo(String value) {
            addCriterion("short_period_one =", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneNotEqualTo(String value) {
            addCriterion("short_period_one <>", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneGreaterThan(String value) {
            addCriterion("short_period_one >", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneGreaterThanOrEqualTo(String value) {
            addCriterion("short_period_one >=", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneLessThan(String value) {
            addCriterion("short_period_one <", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneLessThanOrEqualTo(String value) {
            addCriterion("short_period_one <=", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneLike(String value) {
            addCriterion("short_period_one like", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneNotLike(String value) {
            addCriterion("short_period_one not like", value, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneIn(List<String> values) {
            addCriterion("short_period_one in", values, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneNotIn(List<String> values) {
            addCriterion("short_period_one not in", values, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneBetween(String value1, String value2) {
            addCriterion("short_period_one between", value1, value2, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodOneNotBetween(String value1, String value2) {
            addCriterion("short_period_one not between", value1, value2, "shortPeriodOne");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoIsNull() {
            addCriterion("short_period_two is null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoIsNotNull() {
            addCriterion("short_period_two is not null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoEqualTo(String value) {
            addCriterion("short_period_two =", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoNotEqualTo(String value) {
            addCriterion("short_period_two <>", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoGreaterThan(String value) {
            addCriterion("short_period_two >", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoGreaterThanOrEqualTo(String value) {
            addCriterion("short_period_two >=", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoLessThan(String value) {
            addCriterion("short_period_two <", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoLessThanOrEqualTo(String value) {
            addCriterion("short_period_two <=", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoLike(String value) {
            addCriterion("short_period_two like", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoNotLike(String value) {
            addCriterion("short_period_two not like", value, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoIn(List<String> values) {
            addCriterion("short_period_two in", values, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoNotIn(List<String> values) {
            addCriterion("short_period_two not in", values, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoBetween(String value1, String value2) {
            addCriterion("short_period_two between", value1, value2, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodTwoNotBetween(String value1, String value2) {
            addCriterion("short_period_two not between", value1, value2, "shortPeriodTwo");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeIsNull() {
            addCriterion("short_period_three is null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeIsNotNull() {
            addCriterion("short_period_three is not null");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeEqualTo(String value) {
            addCriterion("short_period_three =", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeNotEqualTo(String value) {
            addCriterion("short_period_three <>", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeGreaterThan(String value) {
            addCriterion("short_period_three >", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeGreaterThanOrEqualTo(String value) {
            addCriterion("short_period_three >=", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeLessThan(String value) {
            addCriterion("short_period_three <", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeLessThanOrEqualTo(String value) {
            addCriterion("short_period_three <=", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeLike(String value) {
            addCriterion("short_period_three like", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeNotLike(String value) {
            addCriterion("short_period_three not like", value, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeIn(List<String> values) {
            addCriterion("short_period_three in", values, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeNotIn(List<String> values) {
            addCriterion("short_period_three not in", values, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeBetween(String value1, String value2) {
            addCriterion("short_period_three between", value1, value2, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andShortPeriodThreeNotBetween(String value1, String value2) {
            addCriterion("short_period_three not between", value1, value2, "shortPeriodThree");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table target
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 01 12:40:18 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table target
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}