package com.boob.sw.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TodayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public TodayExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("u_id is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("u_id is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Long value) {
            addCriterion("u_id =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Long value) {
            addCriterion("u_id <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Long value) {
            addCriterion("u_id >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Long value) {
            addCriterion("u_id >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Long value) {
            addCriterion("u_id <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Long value) {
            addCriterion("u_id <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Long> values) {
            addCriterion("u_id in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Long> values) {
            addCriterion("u_id not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Long value1, Long value2) {
            addCriterion("u_id between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Long value1, Long value2) {
            addCriterion("u_id not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andPushPlanIsNull() {
            addCriterion("push_plan is null");
            return (Criteria) this;
        }

        public Criteria andPushPlanIsNotNull() {
            addCriterion("push_plan is not null");
            return (Criteria) this;
        }

        public Criteria andPushPlanEqualTo(String value) {
            addCriterion("push_plan =", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanNotEqualTo(String value) {
            addCriterion("push_plan <>", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanGreaterThan(String value) {
            addCriterion("push_plan >", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanGreaterThanOrEqualTo(String value) {
            addCriterion("push_plan >=", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanLessThan(String value) {
            addCriterion("push_plan <", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanLessThanOrEqualTo(String value) {
            addCriterion("push_plan <=", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanLike(String value) {
            addCriterion("push_plan like", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanNotLike(String value) {
            addCriterion("push_plan not like", value, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanIn(List<String> values) {
            addCriterion("push_plan in", values, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanNotIn(List<String> values) {
            addCriterion("push_plan not in", values, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanBetween(String value1, String value2) {
            addCriterion("push_plan between", value1, value2, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPushPlanNotBetween(String value1, String value2) {
            addCriterion("push_plan not between", value1, value2, "pushPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanIsNull() {
            addCriterion("pull_plan is null");
            return (Criteria) this;
        }

        public Criteria andPullPlanIsNotNull() {
            addCriterion("pull_plan is not null");
            return (Criteria) this;
        }

        public Criteria andPullPlanEqualTo(String value) {
            addCriterion("pull_plan =", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanNotEqualTo(String value) {
            addCriterion("pull_plan <>", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanGreaterThan(String value) {
            addCriterion("pull_plan >", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanGreaterThanOrEqualTo(String value) {
            addCriterion("pull_plan >=", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanLessThan(String value) {
            addCriterion("pull_plan <", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanLessThanOrEqualTo(String value) {
            addCriterion("pull_plan <=", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanLike(String value) {
            addCriterion("pull_plan like", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanNotLike(String value) {
            addCriterion("pull_plan not like", value, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanIn(List<String> values) {
            addCriterion("pull_plan in", values, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanNotIn(List<String> values) {
            addCriterion("pull_plan not in", values, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanBetween(String value1, String value2) {
            addCriterion("pull_plan between", value1, value2, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andPullPlanNotBetween(String value1, String value2) {
            addCriterion("pull_plan not between", value1, value2, "pullPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanIsNull() {
            addCriterion("leg_plan is null");
            return (Criteria) this;
        }

        public Criteria andLegPlanIsNotNull() {
            addCriterion("leg_plan is not null");
            return (Criteria) this;
        }

        public Criteria andLegPlanEqualTo(String value) {
            addCriterion("leg_plan =", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanNotEqualTo(String value) {
            addCriterion("leg_plan <>", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanGreaterThan(String value) {
            addCriterion("leg_plan >", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanGreaterThanOrEqualTo(String value) {
            addCriterion("leg_plan >=", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanLessThan(String value) {
            addCriterion("leg_plan <", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanLessThanOrEqualTo(String value) {
            addCriterion("leg_plan <=", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanLike(String value) {
            addCriterion("leg_plan like", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanNotLike(String value) {
            addCriterion("leg_plan not like", value, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanIn(List<String> values) {
            addCriterion("leg_plan in", values, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanNotIn(List<String> values) {
            addCriterion("leg_plan not in", values, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanBetween(String value1, String value2) {
            addCriterion("leg_plan between", value1, value2, "legPlan");
            return (Criteria) this;
        }

        public Criteria andLegPlanNotBetween(String value1, String value2) {
            addCriterion("leg_plan not between", value1, value2, "legPlan");
            return (Criteria) this;
        }

        public Criteria andPushFinishIsNull() {
            addCriterion("push_finish is null");
            return (Criteria) this;
        }

        public Criteria andPushFinishIsNotNull() {
            addCriterion("push_finish is not null");
            return (Criteria) this;
        }

        public Criteria andPushFinishEqualTo(String value) {
            addCriterion("push_finish =", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishNotEqualTo(String value) {
            addCriterion("push_finish <>", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishGreaterThan(String value) {
            addCriterion("push_finish >", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishGreaterThanOrEqualTo(String value) {
            addCriterion("push_finish >=", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishLessThan(String value) {
            addCriterion("push_finish <", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishLessThanOrEqualTo(String value) {
            addCriterion("push_finish <=", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishLike(String value) {
            addCriterion("push_finish like", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishNotLike(String value) {
            addCriterion("push_finish not like", value, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishIn(List<String> values) {
            addCriterion("push_finish in", values, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishNotIn(List<String> values) {
            addCriterion("push_finish not in", values, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishBetween(String value1, String value2) {
            addCriterion("push_finish between", value1, value2, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPushFinishNotBetween(String value1, String value2) {
            addCriterion("push_finish not between", value1, value2, "pushFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishIsNull() {
            addCriterion("pull_finish is null");
            return (Criteria) this;
        }

        public Criteria andPullFinishIsNotNull() {
            addCriterion("pull_finish is not null");
            return (Criteria) this;
        }

        public Criteria andPullFinishEqualTo(String value) {
            addCriterion("pull_finish =", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishNotEqualTo(String value) {
            addCriterion("pull_finish <>", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishGreaterThan(String value) {
            addCriterion("pull_finish >", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishGreaterThanOrEqualTo(String value) {
            addCriterion("pull_finish >=", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishLessThan(String value) {
            addCriterion("pull_finish <", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishLessThanOrEqualTo(String value) {
            addCriterion("pull_finish <=", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishLike(String value) {
            addCriterion("pull_finish like", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishNotLike(String value) {
            addCriterion("pull_finish not like", value, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishIn(List<String> values) {
            addCriterion("pull_finish in", values, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishNotIn(List<String> values) {
            addCriterion("pull_finish not in", values, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishBetween(String value1, String value2) {
            addCriterion("pull_finish between", value1, value2, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andPullFinishNotBetween(String value1, String value2) {
            addCriterion("pull_finish not between", value1, value2, "pullFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishIsNull() {
            addCriterion("leg_finish is null");
            return (Criteria) this;
        }

        public Criteria andLegFinishIsNotNull() {
            addCriterion("leg_finish is not null");
            return (Criteria) this;
        }

        public Criteria andLegFinishEqualTo(String value) {
            addCriterion("leg_finish =", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishNotEqualTo(String value) {
            addCriterion("leg_finish <>", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishGreaterThan(String value) {
            addCriterion("leg_finish >", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishGreaterThanOrEqualTo(String value) {
            addCriterion("leg_finish >=", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishLessThan(String value) {
            addCriterion("leg_finish <", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishLessThanOrEqualTo(String value) {
            addCriterion("leg_finish <=", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishLike(String value) {
            addCriterion("leg_finish like", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishNotLike(String value) {
            addCriterion("leg_finish not like", value, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishIn(List<String> values) {
            addCriterion("leg_finish in", values, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishNotIn(List<String> values) {
            addCriterion("leg_finish not in", values, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishBetween(String value1, String value2) {
            addCriterion("leg_finish between", value1, value2, "legFinish");
            return (Criteria) this;
        }

        public Criteria andLegFinishNotBetween(String value1, String value2) {
            addCriterion("leg_finish not between", value1, value2, "legFinish");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table today
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 01 12:40:18 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table today
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}