package com.boob.sw.model;

import java.util.Date;

public class Today {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.u_id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.push_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String pushPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.pull_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String pullPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.leg_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String legPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.push_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String pushFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.pull_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String pullFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.leg_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private String legFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.gmt_created
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column today.gmt_modified
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.id
     *
     * @return the value of today.id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.id
     *
     * @param id the value for today.id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.u_id
     *
     * @return the value of today.u_id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.u_id
     *
     * @param uId the value for today.u_id
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.push_plan
     *
     * @return the value of today.push_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getPushPlan() {
        return pushPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.push_plan
     *
     * @param pushPlan the value for today.push_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setPushPlan(String pushPlan) {
        this.pushPlan = pushPlan == null ? null : pushPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.pull_plan
     *
     * @return the value of today.pull_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getPullPlan() {
        return pullPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.pull_plan
     *
     * @param pullPlan the value for today.pull_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setPullPlan(String pullPlan) {
        this.pullPlan = pullPlan == null ? null : pullPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.leg_plan
     *
     * @return the value of today.leg_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getLegPlan() {
        return legPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.leg_plan
     *
     * @param legPlan the value for today.leg_plan
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setLegPlan(String legPlan) {
        this.legPlan = legPlan == null ? null : legPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.push_finish
     *
     * @return the value of today.push_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getPushFinish() {
        return pushFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.push_finish
     *
     * @param pushFinish the value for today.push_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setPushFinish(String pushFinish) {
        this.pushFinish = pushFinish == null ? null : pushFinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.pull_finish
     *
     * @return the value of today.pull_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getPullFinish() {
        return pullFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.pull_finish
     *
     * @param pullFinish the value for today.pull_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setPullFinish(String pullFinish) {
        this.pullFinish = pullFinish == null ? null : pullFinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.leg_finish
     *
     * @return the value of today.leg_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public String getLegFinish() {
        return legFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.leg_finish
     *
     * @param legFinish the value for today.leg_finish
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setLegFinish(String legFinish) {
        this.legFinish = legFinish == null ? null : legFinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.gmt_created
     *
     * @return the value of today.gmt_created
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.gmt_created
     *
     * @param gmtCreated the value for today.gmt_created
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column today.gmt_modified
     *
     * @return the value of today.gmt_modified
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column today.gmt_modified
     *
     * @param gmtModified the value for today.gmt_modified
     *
     * @mbg.generated Thu Jan 23 18:51:15 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}