package com.boob.sw.mapper;

import com.boob.sw.model.Comments;
import com.boob.sw.model.CommentsExample;
import com.boob.sw.model.CommentsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    long countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insert(CommentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insertSelective(CommentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<CommentsWithBLOBs> selectByExampleWithBLOBsWithRowbounds(CommentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<CommentsWithBLOBs> selectByExampleWithBLOBs(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<Comments> selectByExampleWithRowbounds(CommentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    CommentsWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") CommentsWithBLOBs record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CommentsWithBLOBs record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeySelective(CommentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CommentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKey(Comments record);
}