package com.boob.sw.mapper;

import com.boob.sw.model.OrganMidUser;
import com.boob.sw.model.OrganMidUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrganMidUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    long countByExample(OrganMidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int deleteByExample(OrganMidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int insert(OrganMidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int insertSelective(OrganMidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    List<OrganMidUser> selectByExampleWithRowbounds(OrganMidUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    List<OrganMidUser> selectByExample(OrganMidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    OrganMidUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrganMidUser record, @Param("example") OrganMidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int updateByExample(@Param("record") OrganMidUser record, @Param("example") OrganMidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int updateByPrimaryKeySelective(OrganMidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_mid_user
     *
     * @mbg.generated Thu Jan 30 18:38:51 CST 2020
     */
    int updateByPrimaryKey(OrganMidUser record);
}