package com.boob.sw.mapper;

import com.boob.sw.model.SendUs;
import com.boob.sw.model.SendUsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SendUsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    long countByExample(SendUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int deleteByExample(SendUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int insert(SendUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int insertSelective(SendUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    List<SendUs> selectByExampleWithRowbounds(SendUsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    List<SendUs> selectByExample(SendUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    SendUs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SendUs record, @Param("example") SendUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int updateByExample(@Param("record") SendUs record, @Param("example") SendUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int updateByPrimaryKeySelective(SendUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_us
     *
     * @mbg.generated Sat Feb 01 12:40:18 CST 2020
     */
    int updateByPrimaryKey(SendUs record);
}