package com.boob.sw.mapper;

import com.boob.sw.model.ShopClass;
import com.boob.sw.model.ShopClassExample;
import com.boob.sw.model.ShopClassWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShopClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    long countByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insert(ShopClassWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insertSelective(ShopClassWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<ShopClassWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ShopClassExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<ShopClassWithBLOBs> selectByExampleWithBLOBs(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<ShopClass> selectByExampleWithRowbounds(ShopClassExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<ShopClass> selectByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    ShopClassWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShopClassWithBLOBs record, @Param("example") ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ShopClassWithBLOBs record, @Param("example") ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExample(@Param("record") ShopClass record, @Param("example") ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeySelective(ShopClassWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ShopClassWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKey(ShopClass record);
}