package com.boob.sw.mapper;

import com.boob.sw.model.Superior;
import com.boob.sw.model.SuperiorExample;
import com.boob.sw.model.SuperiorWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SuperiorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    long countByExample(SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByExample(SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insert(SuperiorWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int insertSelective(SuperiorWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<SuperiorWithBLOBs> selectByExampleWithBLOBsWithRowbounds(SuperiorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<SuperiorWithBLOBs> selectByExampleWithBLOBs(SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<Superior> selectByExampleWithRowbounds(SuperiorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    List<Superior> selectByExample(SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    SuperiorWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") SuperiorWithBLOBs record, @Param("example") SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SuperiorWithBLOBs record, @Param("example") SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByExample(@Param("record") Superior record, @Param("example") SuperiorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeySelective(SuperiorWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SuperiorWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superior
     *
     * @mbg.generated Sun Jan 19 19:51:01 CST 2020
     */
    int updateByPrimaryKey(Superior record);
}